spring:
  application:
    name: seckill-product
  datasource:
    url: jdbc:mysql:///seckill?useUnicode=true&characterEncoding=UTF8&useSSL=true
    username: root
    password: root
server:
  port: 11021
eureka:
  instance:
    #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 1
    #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/

swagger:
  # 是否启用swagger，默认：true
  enabled: true
  # swagger扫描的基础包，默认：全扫描
  base-package: com.scorpio.product.controller
  # 需要处理的基础URL规则，默认：/**
  base-path: /**
  # 描述
  description: 产品接口
  # 需要排除的URL规则，默认：空
  # exclude-path: /error
  # 标题
  title: com.scorpio.product.controller
  # 版本
  version: 0.0.1-SNAPSHOT

mybatis:
  basepackage: com.scorpio.product.mapper
  mapperLocations: classpath:mapper/**/*.xml
logging:
  level:
    tk.mybatis: DEBUG
    com.scorpio.product: DEBUG
